version: "3.9"

services:
  web:
    build: ./services/web
    restart: always
    command: python -u run.py
    ports:
      - "8000:8080"
    depends_on:
      - db
  db:
      image: postgres:13
      restart: always
      volumes:
        - postgres_data:/db/postgresql/data/
      environment:
        - POSTGRES_USER=hello_flask
        - POSTGRES_PASSWORD=hello_flask
        - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: